FROM node:16-alpine as builder
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY . .    
RUN npm run build

# Run Phase
FROM node:16-alpine
WORKDIR /usr/app
COPY package.json ./
RUN npm install
COPY --from=builder /app/dist .
CMD ["node", "server.js"]