# Specify Base Image
FROM node:16-alpine

# Work Directory
WORKDIR /usr/app

# COPY Files
COPY package.json .

# Install Dependencies
RUN npm install

COPY . .
# Startup Command
CMD ["npm", "run", "serve"]